config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'products#home'

  get '/admin', to: 'admin/products#index'

  get '/facility' => 'pages#facilities'

  resources :categories

  resources :products

  namespace :admin do
    resources :products
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :products

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  self.per_page = 12
  has_and_belongs_to_many :categories

  validates :title, :description, :price, presence: true
  validate :has_at_least_one_category

  def has_category?(category)
    self.categories.include? category
  end

  def set_categories(category_hash)
    if category_hash
      category_hash.each_key do |key|
        self.categories << Category.find(key)
      end
    end
  end

  private
  def has_at_least_one_category
    if self.categories.length < 1
      errors.add(:product, "needs to belong to at least one category")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_user!
  before_filter :verify_admin

  def index
    @products = Product.paginate(:page => params[:page], :per_page => 10).order(:id)
  end

  def show
    @product = Product.find(params[:id])
    if request.xhr?
      render "_modal", layout: false
    end
  end

  def new
    @product = Product.new
    @categories = Category.order(:name)
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.order(:name)
  end

  def create
    @product = Product.new(product_params)
    @categories = Category.order(:name)
    @product.set_categories(params[:category])

    if @product.save
      flash[:success] = "Product successfully created"
      redirect_to admin_products_path
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])
    @categories = Category.order(:name)
    @product.categories = []
    @product.set_categories(params[:category])

    if @product.update(product_params)
      flash[:success] = "Product successfully updated"
      redirect_to admin_products_path
    else
      render "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:info] = "Product successfully deleted"
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :picture_link)
  end

  def verify_admin
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.paginate(:page => params[:page])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def facilities
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
    if request.xhr?
      render "_modal", layout: false
    end
  end

  def home
    @products = Product.order("RANDOM()").limit(2)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.haml
- if @product.errors.any?
  #error_explanation
    .alert.alert-danger
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

.form-container.form-inline
  = form_for [:admin, @product] do |f|
    .form-group.col-md-6.col-xs-12.text-center
      %p= f.label :title
      %p= f.text_field :title
    .form-group.col-md-6.col-xs-12.text-center
      %p= f.label :price
      %p= f.number_field :price, :step => 0.01
    .form-group.col-md-6.col-xs-12.text-center
      %p= f.label :description
      %p= f.text_area :description
    .form-group.col-md-6.col-xs-12.text-center
      %p= f.label :picture_link
      %p= f.text_field :picture_link

    .form-group.form-checkbox.col-md-12.col-xs-12
      %p.text-center= f.label :categories
      %p
        - @categories.each do |category|
          .checkbox-list
            - if @product.has_category?(category)
              %input{name: "category[#{category.id}]", type: "checkbox", checked: "" }
            - else
              %input{name: "category[#{category.id}]", type: "checkbox"}
            = category.name
    .form-group.col-md-12.col-xs-12.text-center
      %input.btn.btn-default{type: "submit", value: "Save Changes"}
  .form-group.col-md-12.col-xs-12.text-center
    = link_to 'Back', admin_products_path, class: "btn btn-default back-button"

app/views/admin/products/_modal.html.haml
.modal-header
  %button.close{"type" => "button", "data-dismiss" => "modal"}
    %span.glyphicon.glyphicon-remove
  %h2.modal-title= @product.title
.modal-body
  %p#product-img-modal
    = image_tag @product.picture_link
  %h4#product-price-modal
    = "$#{Money.us_dollar(@product.price*100)}"

  %p#product-desc-modal= @product.description
  = link_to "Edit", edit_admin_product_path(@product), class: "btn btn-default"
  = link_to "Delete", admin_product_path(@product), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

app/views/admin/products/edit.html.haml
%h1.text-center Edit Product
= render 'form'

app/views/admin/products/index.html.haml
.feature-heading.text-center ADMIN

= link_to 'Add Product', new_admin_product_path, class: "btn btn-default"

%table.table.table-responsive.table-hover
  %tr
    %th Pic
    %th Title
    %th.hide-on-mobile Description
    %th Price
    %th
    %th
  -@products.each do |product|
    %tr
      %td.admin-image
        = image_tag product.picture_link
      %td.admin-product-link
        =link_to "#{product.title}", admin_product_path(product)
      - if product.description.length >= 40
        %td.hide-on-mobile= product.description[0..39] + "..."
      - else
        %td.hide-on-mobile= product.description
      %td= "$#{Money.us_dollar(product.price*100)}"
      %td
        = link_to edit_admin_product_path(product) do
          %span.glyphicon.glyphicon-pencil
      %td
        = link_to admin_product_path(product), method: :delete, data: {confirm: "Are you sure?"} do
          %span.glyphicon.glyphicon-trash

.custom-pagination.text-center
  = will_paginate @products, :previous_label => raw("<span class='glyphicon glyphicon-arrow-left'></span>"), :next_label => raw("<span class='glyphicon glyphicon-arrow-right'></span>")

app/views/admin/products/new.html.haml
%h1.text-center New Product
= render 'form'

app/views/admin/products/show.html.haml
.text-center
  %p
    = image_tag @product.picture_link
  %h4
    = @product.title
    = "| $#{Money.us_dollar(@product.price*100)}"

  %p
    = "Categories: "
    .list-categories
      %ul
        - @product.categories.each do |category|
          %li.product-categories= category.name
  %p= @product.description

  = link_to "Edit", edit_admin_product_path(@product), class: "btn btn-default"
  = link_to "Delete", admin_product_path(@product), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
  = link_to "Back", admin_products_path, class: "btn btn-default"

app/views/categories/_sidebar.html.haml
.sidebar-container
  =render 'layouts/search'
  .panel.panel-info
    .panel-body
      - Category.all.each do |category|
        .row.category-list{ id: "categoryid_#{category.id}" }
          .col-md-12.col-xs-12.category-title= link_to category.name.upcase, category_path(category)

app/views/categories/show.html.haml
=render 'categories/sidebar'
.main-container
  .feature-heading.text-center= @category.name
  = render 'products/show'


.custom-pagination.text-center
  = will_paginate @products, :previous_label => raw("<span class='glyphicon glyphicon-arrow-left'></span>"), :next_label => raw("<span class='glyphicon glyphicon-arrow-right'></span>")

app/views/layouts/_contact.html.haml
.modal.fade#contact-overlay{"tabindex" => "-1", "role" => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"type" => "button", "data-dismiss" => "modal"}
          %span.glyphicon.glyphicon-remove
        %h2.modal-title= "Contact Us!"
      .modal-body

        %p
        = "Address: 633 Folsom Street, "
        = "San Francisco, CA 94107"

        %p
        = "Telephone: 123-456-7890"

        %p
        = "We welcome all inquiries. Please fill out the form below, and our representative will get back to you shortly."

        .text-center
          = form_tag '#' do
            %p
              .email-label= label_tag :name, "Name"
              .form-group= text_field_tag :name
            %p
              .email-label= label_tag :email, "Email"
              .form-group= text_field_tag :Email
            %p
              .email-label= label_tag :message, "Message"
              .form-group= text_area_tag :message
            %input.btn.btn-default{type: "submit", value: "Send Email"}

app/views/layouts/_flash_alerts.html.haml
- flash.each do |message_type, message|
  .alert{:class => "alert-#{message_type}"}
    = message

app/views/layouts/_navbar.html.haml
.navbar.navbar-inverse.panel-primary.navbar-fixed-top
  .navbar-header
    %button.navbar-toggle{type: "button", "data-toggle" => "collapse", "data-target" => ".bs-navbar-collapse" }
      %span.sr-only="Toggle navigation"
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to 'THE STORE', '/', { class: "navbar-brand" }
  .collapse.navbar-collapse.bs-navbar-collapse
    %ul.nav.navbar-nav
      %li.dropdown
        = link_to raw("Categories <span class='caret'></span>"),"#", {"class"=>"dropdown-toggle","data-toggle"=>"dropdown", "role"=>"button","aria-haspopup"=>"true", "aria-expanded"=>"false"}
        %ul.dropdown-menu
          - Category.all.each do |category|
            %li= link_to category.name, category_path(category)
      %li= link_to "Our Facility", "/facility"

    %ul.nav.navbar-nav.navbar-right
      - if current_user && current_user.admin?
        %li= link_to "Inventory Admin", admin_path
      - if current_user
        %li= link_to "Logout", '/users/sign_out', method: :delete
      %li.contact-page{ "data-toggle" => "modal", "data-target" => "#contact-overlay"}= link_to "Contact Us", '#'

app/views/layouts/_search.html.haml
%form{"role"=>"search"}
  .form-group.search-form
    %input.form-control.col-md-8.col-sm-8.col-xs-8{"type"=>"text", "placeholder"=>"Search"}
    %button.btn.btn-default.col-md-2.col-sm-2.col-xs-2{"type"=>"submit"}
      %span.glyphicon.glyphicon-search

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %title Shoppe
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=PT+Sans", :rel => "stylesheet", :type =>"text/css"}
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", :integrity => "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7", :rel => "stylesheet"}
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css", :integrity => "sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r", :rel => "stylesheet"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"}
  %body
    .container
      = render 'layouts/navbar'
      = render 'layouts/contact'
      .modal.fade#product-modal{"tabindex" => "-1", "role" => "dialog"}
        .modal-dialog
          .modal-content.text-center
      - if notice
        .alert.alert-success= notice
      - if alert
        .alert.alert-danger= alert
      = yield

app/views/pages/facilities.html.haml
.facilities-container
  .row
    .col-lg-1
    .col-lg-10.col-md-12.col-sm-12.facilities-divider
      .facilities-header
        %h1.facilities-title="Our Facility"
      %img{src: "https://chinabdotorg.files.wordpress.com/2012/02/assembly-line-anta.jpg", width: "625"}
      %p.facilities-subtitle="Who we are"
      %p.facilities-description="Factories arose with the introduction of machinery during the Industrial Revolution when the capital and space requirements became too great for cottage industry or workshops. Early factories that contained small amounts of machinery, such as one or two spinning mules, and fewer than a dozen workers have been called \"glorified workshops\"."
      %p.facilities-description="Most modern factories have large warehouses or warehouse-like facilities that contain heavy equipment used for assembly line production. Large factories tend to be located with access to multiple modes of transportation, with some having rail, highway and water loading and unloading facilities."
      %p.facilities-description="Factories may either make discrete products or some type of material continuously produced such as chemicals, pulp and paper, or refined oil products. Factories manufacturing chemicals are often called plants and may have most of their equipment – tanks, pressure vessels, chemical reactors, pumps and piping – outdoors and operated from control rooms. Oil refineries have most of their equipment outdoors."
      %p.facilities-description="Discrete products may be final consumer goods, or parts and sub-assemblies which are made into final products elsewhere. Factories may be supplied parts from elsewhere or make them from raw materials. Continuous production industries typically use heat or electricity to transform streams of raw materials into finished products."
      %video#video-mechanic{:controls => "controls"}
        %source{:src => "http://www.americanapparel.net/storefront/v3campaigns/factorytour/en/video/12_mechanic.mp4"}/
      %img{src: "http://eco220.ru/wp-content/uploads/2014/06/spacex-team-4.jpg"}
      %p.facilities-subtitle="State of the art equipment"
      %p.facilities-description="The term \"state of the art\" (sometimes \"cutting edge\") refers to the highest level of general development, as of a device, technique, or scientific field achieved at a particular time. It also refers to the level of development (as of a device, procedure, process, technique, or science) reached at any particular time as a result of the common methodologies employed. The term has been used since 1910, and has become both a common term in advertising and marketing, and a legally significant phrase with respect to both patent law and tort liability. In advertising, the phrase is often used to convey that a product is made with the best possible technology, but it has been noted that \"the term 'state of the art' requires little proof on the part of advertisers\", as it is considered mere puffery.[1] The use of the term in patent law, by contrast, \"does not connote even superiority, let alone the superlative quality the ad writers would have us ascribe to the term\""
      %video#video-sew{:controls => "controls"}
        %source{:src => "http://www.americanapparel.net/storefront/v3campaigns/factorytour/en/video/11_6thSew.mp4"}/

app/views/products/_modal.html.haml
.modal-header
  %button.close{"type" => "button", "data-dismiss" => "modal"}
    %span.glyphicon.glyphicon-remove
  %h2.modal-title= @product.title
.modal-body
  #product-img-modal.vertical-center
    = image_tag @product.picture_link
  %h4#product-price-modal
    = "$#{Money.us_dollar(@product.price*100)}"

  %p#product-desc-modal= @product.description

app/views/products/_show.html.haml
.row
  - @products.each do |product|
    .col-md-4.col-sm-6.col-xs-12.product-display-image
      .list-img-container
        .col-md-12.col-sm-12.col-xs-12.vertical-center.no-padding
          = image_tag product.picture_link
      .col-md-12.col-sm-12.col-xs-12.vertical-center.product-title-box
        = link_to product.title, product_path(product)
        = " | $#{Money.us_dollar(product.price*100)}"

app/views/products/home.html.haml
=render 'categories/sidebar'
.main-container
  .row.carousel-holder
    .col-md-12
      #carousel-example-generic.carousel.slide{"data-ride" => "carousel" }
        .carousel-inner
          .item.active
            %img.slide-image{ src: "http://i.nordstromimage.com/images/default/shop/image/shops/mens-shoes-boots/2012/1105/mens-shoes-made-in-america_header.jpg"}
          .item
            %img.slide-image{ src: "http://i.nordstromimage.com/images/default/shop/image/shops/mens-shoes/2016/0125/mens-dress-loafers_header.jpg"}
          .item
            %img.slide-image{ src: "http://blog.schuh.co.uk/wp-content/uploads/2015/08/celebrities-wearing-lace-up-heels-schuh-blog-header.jpg"}
        %a.left.carousel-control{"data-slide" => "prev", href: "#carousel-example-generic"}
          %span.glyphicon.glyphicon-chevron-left
        %a.right.carousel-control{"data-slide" => "next", href: "#carousel-example-generic"}
          %span.glyphicon.glyphicon-chevron-right

  .row
    - @products.each do |product|
      .col-md-6.col-sm-6.col-xs-12.product-display-image.feature-products
        .featured-img-container
          .col-md-12.col-sm-12.col-xs-12.feature-product-image
            = image_tag product.picture_link
        .col-md-12.col-sm-12.col-xs-12.feature-left-container
          .col-md-12.col-sm-12.col-xs-12.feature-product-title
            = link_to product.title, product_path(product)
          .col-md-12.col-sm-12.col-xs-12.feature-product-desc
            = product.description

app/views/products/show.html.haml
.text-center
  %p
    = image_tag @product.picture_link
  %h4
    = @product.title
    ="| $#{Money.us_dollar(@product.price*100)}"

  %p
    = "Categories: "
    .list-categories
      %ul
        - @product.categories.each do |category|
          %li.product-categories= category.name
  %p= @product.description

  = link_to "Back to Home", root_path, class: "btn btn-default"